openapi: 3.0.0
info:
  title: WSO2 Identity Server - EKYC API Definition
  description: This document specifies a **RESTful API** for **WSO2 Identity Server EKYC**
  contact:
    name: WSO2
    url: http://wso2.com/products/identity-server/
    email: architecture@wso2.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "v1"
servers:
  - url: https://localhost:9443/t/{tenant-domain}/api/server/v1
    variables:
      tenant-domain:
        default: carbon.super
security:
  - OAuth2: []
  - BasicAuth: []
paths:
  /ekyc:
    get:
      tags:
        - EKYC
      summary: Get an ekyc configuration
      description: |
        This API provides the capability to get an ekyc configuration. <br>
          <b>Permission required:</b> <br>
            * /permission/admin/manage/identity/configmgt/view <br>
          <b>Scope required:</b> <br>
            * internal_config_mgt_view
      operationId: getEKYCConfiguration
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EKYCConfiguration'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - EKYC
      summary: Create an EKYC configuration
      description: |
        This API provides the capability to create an ekyc connection.<br>
          <b>Permission required:</b> <br>
            * /permission/admin/manage/identity/configmgt/add <br>
          <b>Scope required:</b> <br>
            * internal_config_mgt_add
      operationId: createEKYCConfiguration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EKYCConfiguration'
            example:
              url: https://localhost:5443
              apiKey: demoApiKey
              apiSecret: demoApiSecret
              callbackUrl: https://localhost:9000/myaccount/personal-info
              services:
                - testService
              claimsMapping:
                family_name: http://wso2.org/claims/lastname
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EKYCConfiguration'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - EKYC
      summary: Update an EKYC configuration
      description: |
        This API provides the capability to update an ekyc connection.<br>
          <b>Permission required:</b> <br>
            * /permission/admin/manage/identity/configmgt/add <br>
          <b>Scope required:</b> <br>
            * internal_config_mgt_add
      operationId: updateEKYCConfiguration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EKYCConfiguration'
            example:
              url: https://localhost:5443
              apiKey: demoApiKey
              apiSecret: demoApiSecret
              callbackUrl: https://localhost:9000/myaccount/personal-info
              services:
                - testService
              claimsMapping:
                family_name: http://wso2.org/claims/lastname
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EKYCConfiguration'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - EKYC
      summary: Delete an EKYC configuration
      description: |
        This API provides the capability to delete an ekyc connection.<br>
          <b>Permission required:</b> <br>
            * /permission/admin/manage/identity/configmgt/add <br>
          <b>Scope required:</b> <br>
            * internal_config_mgt_add
      operationId: deleteEKYCConfiguration
      responses:
        "200":
          description: Successful Response
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
          example: NSM-00000
        message:
          type: string
          example: Some Error Message
        description:
          type: string
          example: Some Error Description
        traceId:
          type: string
          example: e0fbcfeb-3617-43c4-8dd0-7b7d38e13047
    EKYCConfiguration:
      required:
        - url
        - apiKey
        - apiSecret
        - callbackUrl
      type: object
      properties:
        url:
          type: string
        apiKey:
          type: string
        apiSecret:
          type: string
        callbackUrl:
          type: string
        services:
          type: array
          items:
            type: string
        claimsMapping:
          type: object
          additionalProperties:
            type: string